#!/usr/bin/env python3

import argparse
import html

import app

def main():
    ap = argparse.ArgumentParser()
    types = list(sorted(app.input_type_to_resolver.keys()))
    ap.add_argument('-t', '--type', choices=types, metavar='TYPE', default='url-doi-isbn')
    ap.add_argument('-d', '--date-format', default='%Y-%m-%d')
    ap.add_argument('ident', metavar='URL-OR-ID')
    options = ap.parse_args()
    resolver = app.input_type_to_resolver[options.type]
    for item in resolver(options.ident, options.date_format):
        print(html.unescape(item), end='\n\n')

if __name__ == '__main__':
    main()
